name: icon_font_generator
version: 3.2.0-fork.1
homepage: https://github.com/rbcprolabs/icon_font_generator
description: Convert all *.svg icons from dir to icon-font (.ttf) and generates flutter compatible dart class.

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  recase: ^4.1.0
  args: ^2.4.2
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1

executables:
  icon_font_generator: icon_font_generator
